apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-api-config
data:
  DBUSER: devops_user
  DB: devops_db
  DBHOST: mysql
  DBPORT: "3306"
  PORT: "3001"
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-api-secret
type: Opaque
data:
  DBPASS: cGFzc3dvcmQ= # This is the base64 encoded value of 'password'