apiVersion: v1
kind: Pod
metadata:
  name: backup-access
spec:
  containers:
  - name: backup-access
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: backup-storage
      mountPath: /backup
  volumes:
  - name: backup-storage
    persistentVolumeClaim:
      claimName: backup-pvc